---
development:
  dialect: postgres
  database: curso
  user: pato
  password: 1337
  host: 127.0.0.1
  pool: 5
  port: 5432

#test:
#  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/curso-test?sslmode=disable"}}
#
production:
  url: {{envOr "DATABASE_URL" "postgres://pato:1337@127.0.0.1:5432/curso?sslmode=disable"}}

# docker run --name pyc-postgres -e POSTGRES_PASSWORD=1337 -p 5432:5432 -d postgres
# sudo docker run --name forum \ # uncomment this and paste in bash
#   -e POSTGRES_PASSWORD=1337 \
# -e POSTGRES_USER=pato \
# -e POSTGRES_DB=curso \
#  -p 5432:5432 -d postgres

